# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XOR.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(844, 542)
        MainWindow.setMinimumSize(QtCore.QSize(844, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.encryptionFrame = QtWidgets.QFrame(self.centralwidget)
        self.encryptionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.encryptionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.encryptionFrame.setObjectName("encryptionFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.encryptionFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textFileButton = QtWidgets.QPushButton(self.encryptionFrame)
        self.textFileButton.setObjectName("textFileButton")
        self.verticalLayout.addWidget(self.textFileButton)
        self.inTextLabel = QtWidgets.QLabel(self.encryptionFrame)
        self.inTextLabel.setObjectName("inTextLabel")
        self.verticalLayout.addWidget(self.inTextLabel)
        self.inTextEdit = QtWidgets.QTextEdit(self.encryptionFrame)
        self.inTextEdit.setObjectName("inTextEdit")
        self.verticalLayout.addWidget(self.inTextEdit)
        self.textRadioButtonContainer = QtWidgets.QFrame(self.encryptionFrame)
        self.textRadioButtonContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textRadioButtonContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textRadioButtonContainer.setObjectName("textRadioButtonContainer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.textRadioButtonContainer)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.symbolTextRadioButton = QtWidgets.QRadioButton(self.textRadioButtonContainer)
        self.symbolTextRadioButton.setObjectName("symbolTextRadioButton")
        self.horizontalLayout_4.addWidget(self.symbolTextRadioButton)
        self.binaryTextRadioButton = QtWidgets.QRadioButton(self.textRadioButtonContainer)
        self.binaryTextRadioButton.setObjectName("binaryTextRadioButton")
        self.horizontalLayout_4.addWidget(self.binaryTextRadioButton)
        self.hexRadioButton = QtWidgets.QRadioButton(self.textRadioButtonContainer)
        self.hexRadioButton.setObjectName("hexRadioButton")
        self.horizontalLayout_4.addWidget(self.hexRadioButton)
        self.verticalLayout.addWidget(self.textRadioButtonContainer)
        self.keyButtonContainer = QtWidgets.QFrame(self.encryptionFrame)
        self.keyButtonContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keyButtonContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keyButtonContainer.setObjectName("keyButtonContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.keyButtonContainer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.keyFileButton = QtWidgets.QPushButton(self.keyButtonContainer)
        self.keyFileButton.setObjectName("keyFileButton")
        self.horizontalLayout_2.addWidget(self.keyFileButton)
        self.verticalLayout.addWidget(self.keyButtonContainer)
        self.label = QtWidgets.QLabel(self.encryptionFrame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.encryptionFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.lineEditPolynom = QtWidgets.QLineEdit(self.frame)
        self.lineEditPolynom.setObjectName("lineEditPolynom")
        self.horizontalLayout_6.addWidget(self.lineEditPolynom)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.encryptionFrame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.lineEditInitial = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditInitial.setObjectName("lineEditInitial")
        self.horizontalLayout_7.addWidget(self.lineEditInitial)
        self.verticalLayout.addWidget(self.frame_2)
        self.keyGenerateButton = QtWidgets.QPushButton(self.encryptionFrame)
        self.keyGenerateButton.setObjectName("keyGenerateButton")
        self.verticalLayout.addWidget(self.keyGenerateButton)
        self.keyLabel = QtWidgets.QLabel(self.encryptionFrame)
        self.keyLabel.setObjectName("keyLabel")
        self.verticalLayout.addWidget(self.keyLabel)
        self.keyEdit = QtWidgets.QTextEdit(self.encryptionFrame)
        self.keyEdit.setObjectName("keyEdit")
        self.verticalLayout.addWidget(self.keyEdit)
        self.keyRadioButtonContainer = QtWidgets.QFrame(self.encryptionFrame)
        self.keyRadioButtonContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keyRadioButtonContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keyRadioButtonContainer.setObjectName("keyRadioButtonContainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.keyRadioButtonContainer)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.symbolKeyRadioButton = QtWidgets.QRadioButton(self.keyRadioButtonContainer)
        self.symbolKeyRadioButton.setObjectName("symbolKeyRadioButton")
        self.horizontalLayout_3.addWidget(self.symbolKeyRadioButton)
        self.binKeyRadioButton = QtWidgets.QRadioButton(self.keyRadioButtonContainer)
        self.binKeyRadioButton.setObjectName("binKeyRadioButton")
        self.horizontalLayout_3.addWidget(self.binKeyRadioButton)
        self.hexKeyRadioButton = QtWidgets.QRadioButton(self.keyRadioButtonContainer)
        self.hexKeyRadioButton.setObjectName("hexKeyRadioButton")
        self.horizontalLayout_3.addWidget(self.hexKeyRadioButton)
        self.verticalLayout.addWidget(self.keyRadioButtonContainer)
        self.encryptButton = QtWidgets.QPushButton(self.encryptionFrame)
        self.encryptButton.setObjectName("encryptButton")
        self.verticalLayout.addWidget(self.encryptButton)
        self.horizontalLayout.addWidget(self.encryptionFrame)
        self.outTextFrame = QtWidgets.QFrame(self.centralwidget)
        self.outTextFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outTextFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outTextFrame.setObjectName("outTextFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.outTextFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outTextLabel = QtWidgets.QLabel(self.outTextFrame)
        self.outTextLabel.setObjectName("outTextLabel")
        self.verticalLayout_2.addWidget(self.outTextLabel)
        self.outTextEdit = QtWidgets.QTextEdit(self.outTextFrame)
        self.outTextEdit.setObjectName("outTextEdit")
        self.verticalLayout_2.addWidget(self.outTextEdit)
        self.outTextRadioButtonContainer = QtWidgets.QFrame(self.outTextFrame)
        self.outTextRadioButtonContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outTextRadioButtonContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outTextRadioButtonContainer.setObjectName("outTextRadioButtonContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.outTextRadioButtonContainer)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.symbolOutTextRadioButton = QtWidgets.QRadioButton(self.outTextRadioButtonContainer)
        self.symbolOutTextRadioButton.setObjectName("symbolOutTextRadioButton")
        self.horizontalLayout_5.addWidget(self.symbolOutTextRadioButton)
        self.binOutTextRadioButton = QtWidgets.QRadioButton(self.outTextRadioButtonContainer)
        self.binOutTextRadioButton.setObjectName("binOutTextRadioButton")
        self.horizontalLayout_5.addWidget(self.binOutTextRadioButton)
        self.hexOutTextRadioButton = QtWidgets.QRadioButton(self.outTextRadioButtonContainer)
        self.hexOutTextRadioButton.setObjectName("hexOutTextRadioButton")
        self.horizontalLayout_5.addWidget(self.hexOutTextRadioButton)
        self.verticalLayout_2.addWidget(self.outTextRadioButtonContainer)
        self.horizontalLayout.addWidget(self.outTextFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XOR шифрование"))
        self.textFileButton.setText(_translate("MainWindow", "Выбрать файл текста для шифрования/расшифровки"))
        self.inTextLabel.setText(_translate("MainWindow", "Входной текст"))
        self.symbolTextRadioButton.setText(_translate("MainWindow", "Символьный вид"))
        self.binaryTextRadioButton.setText(_translate("MainWindow", "Двоичный вид"))
        self.hexRadioButton.setText(_translate("MainWindow", "Шестнадцатеричный вид"))
        self.keyFileButton.setText(_translate("MainWindow", "Выбрать файл ключа"))
        self.label.setText(_translate("MainWindow", "Выбрать полинм (работает только для кнопки \"Сгенерировать ключ\")"))
        self.label_2.setText(_translate("MainWindow", "Полином"))
        self.label_3.setText(_translate("MainWindow", "Начальное значение"))
        self.keyGenerateButton.setText(_translate("MainWindow", "Сгенерировать ключ"))
        self.keyLabel.setText(_translate("MainWindow", "Ключ"))
        self.symbolKeyRadioButton.setText(_translate("MainWindow", "Символьный вид"))
        self.binKeyRadioButton.setText(_translate("MainWindow", "Двоичный вид"))
        self.hexKeyRadioButton.setText(_translate("MainWindow", "Шестнадцатеричный вид"))
        self.encryptButton.setText(_translate("MainWindow", "Зашифровать/расшифровать"))
        self.outTextLabel.setText(_translate("MainWindow", "Выходной текст"))
        self.symbolOutTextRadioButton.setText(_translate("MainWindow", "Символьный вид"))
        self.binOutTextRadioButton.setText(_translate("MainWindow", "Двоичный вид"))
        self.hexOutTextRadioButton.setText(_translate("MainWindow", "Шестнадцатеричный вид"))

