# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSA.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 623)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.lineEditLength = QtWidgets.QLineEdit(self.frame)
        self.lineEditLength.setObjectName("lineEditLength")
        self.verticalLayout.addWidget(self.lineEditLength)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnChooseRSA = QtWidgets.QPushButton(self.frame_2)
        self.btnChooseRSA.setObjectName("btnChooseRSA")
        self.horizontalLayout.addWidget(self.btnChooseRSA)
        self.btnGenerateRandomRSA = QtWidgets.QPushButton(self.frame_2)
        self.btnGenerateRandomRSA.setObjectName("btnGenerateRandomRSA")
        self.horizontalLayout.addWidget(self.btnGenerateRandomRSA)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditP = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditP.setObjectName("lineEditP")
        self.horizontalLayout_2.addWidget(self.lineEditP)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEditQ = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditQ.setObjectName("lineEditQ")
        self.horizontalLayout_2.addWidget(self.lineEditQ)
        self.verticalLayout.addWidget(self.frame_3)
        self.btnGenerateKeys = QtWidgets.QPushButton(self.frame)
        self.btnGenerateKeys.setObjectName("btnGenerateKeys")
        self.verticalLayout.addWidget(self.btnGenerateKeys)
        self.textBrowserKeys = QtWidgets.QTextBrowser(self.frame)
        self.textBrowserKeys.setObjectName("textBrowserKeys")
        self.verticalLayout.addWidget(self.textBrowserKeys)
        self.textBrowserTime = QtWidgets.QTextBrowser(self.frame)
        self.textBrowserTime.setObjectName("textBrowserTime")
        self.verticalLayout.addWidget(self.textBrowserTime)
        self.btnImportKeys = QtWidgets.QPushButton(self.frame)
        self.btnImportKeys.setObjectName("btnImportKeys")
        self.verticalLayout.addWidget(self.btnImportKeys)
        self.btnCreateDESKey = QtWidgets.QPushButton(self.frame)
        self.btnCreateDESKey.setObjectName("btnCreateDESKey")
        self.verticalLayout.addWidget(self.btnCreateDESKey)
        self.lineEditCreatedDESKey = QtWidgets.QLineEdit(self.frame)
        self.lineEditCreatedDESKey.setObjectName("lineEditCreatedDESKey")
        self.verticalLayout.addWidget(self.lineEditCreatedDESKey)
        self.horizontalLayout_4.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.btnChooseDESKey = QtWidgets.QPushButton(self.frame_4)
        self.btnChooseDESKey.setObjectName("btnChooseDESKey")
        self.verticalLayout_2.addWidget(self.btnChooseDESKey)
        self.lineEditDesKey = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditDesKey.setObjectName("lineEditDesKey")
        self.verticalLayout_2.addWidget(self.lineEditDesKey)
        self.btnChooseDESText = QtWidgets.QPushButton(self.frame_4)
        self.btnChooseDESText.setObjectName("btnChooseDESText")
        self.verticalLayout_2.addWidget(self.btnChooseDESText)
        self.checkBoxDecrypt = QtWidgets.QCheckBox(self.frame_4)
        self.checkBoxDecrypt.setObjectName("checkBoxDecrypt")
        self.verticalLayout_2.addWidget(self.checkBoxDecrypt)
        self.textBrowserDesText = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowserDesText.setObjectName("textBrowserDesText")
        self.verticalLayout_2.addWidget(self.textBrowserDesText)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnProcessDES = QtWidgets.QPushButton(self.frame_5)
        self.btnProcessDES.setObjectName("btnProcessDES")
        self.horizontalLayout_3.addWidget(self.btnProcessDES)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.textBrowserDesResult = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowserDesResult.setObjectName("textBrowserDesResult")
        self.verticalLayout_2.addWidget(self.textBrowserDesResult)
        self.horizontalLayout_4.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Длина простых чисел"))
        self.label.setText(_translate("MainWindow", "RSA"))
        self.btnChooseRSA.setText(_translate("MainWindow", "Выбрать файл с числами p и q"))
        self.btnGenerateRandomRSA.setText(_translate("MainWindow", "Сгенерировать p и q случайно"))
        self.label_2.setText(_translate("MainWindow", "p"))
        self.label_3.setText(_translate("MainWindow", "q"))
        self.btnGenerateKeys.setText(_translate("MainWindow", "Сгенерировать ключи для RSA"))
        self.btnImportKeys.setText(_translate("MainWindow", "Импортировать ключи"))
        self.btnCreateDESKey.setText(_translate("MainWindow", "Создать ключ для DES"))
        self.label_4.setText(_translate("MainWindow", "DES"))
        self.btnChooseDESKey.setText(_translate("MainWindow", "Выбрать файл с ключом"))
        self.btnChooseDESText.setText(_translate("MainWindow", "Выбрать файл с текстом"))
        self.checkBoxDecrypt.setText(_translate("MainWindow", "Дешифровать"))
        self.btnProcessDES.setText(_translate("MainWindow", "Обработать"))

