# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Avalanche.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 559)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblBlockCount = QtWidgets.QLabel(self.centralwidget)
        self.lblBlockCount.setObjectName("lblBlockCount")
        self.verticalLayout.addWidget(self.lblBlockCount, 0, QtCore.Qt.AlignHCenter)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEditBlockNum = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditBlockNum.setObjectName("lineEditBlockNum")
        self.horizontalLayout_2.addWidget(self.lineEditBlockNum)
        self.btnChooseBlock = QtWidgets.QPushButton(self.frame_2)
        self.btnChooseBlock.setObjectName("btnChooseBlock")
        self.horizontalLayout_2.addWidget(self.btnChooseBlock)
        self.btnBlocksAverage = QtWidgets.QPushButton(self.frame_2)
        self.btnBlocksAverage.setObjectName("btnBlocksAverage")
        self.horizontalLayout_2.addWidget(self.btnBlocksAverage)
        self.verticalLayout.addWidget(self.frame_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.lineEditInText = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditInText.setEnabled(True)
        self.lineEditInText.setReadOnly(True)
        self.lineEditInText.setObjectName("lineEditInText")
        self.verticalLayout.addWidget(self.lineEditInText)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEditIndex = QtWidgets.QLineEdit(self.frame)
        self.lineEditIndex.setMinimumSize(QtCore.QSize(75, 0))
        self.lineEditIndex.setObjectName("lineEditIndex")
        self.horizontalLayout.addWidget(self.lineEditIndex)
        self.btnProcess = QtWidgets.QPushButton(self.frame)
        self.btnProcess.setMinimumSize(QtCore.QSize(150, 0))
        self.btnProcess.setObjectName("btnProcess")
        self.horizontalLayout.addWidget(self.btnProcess)
        self.btnAverage = QtWidgets.QPushButton(self.frame)
        self.btnAverage.setMinimumSize(QtCore.QSize(150, 0))
        self.btnAverage.setObjectName("btnAverage")
        self.horizontalLayout.addWidget(self.btnAverage)
        self.verticalLayout.addWidget(self.frame)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.lineEditOutText = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditOutText.setEnabled(True)
        self.lineEditOutText.setReadOnly(True)
        self.lineEditOutText.setObjectName("lineEditOutText")
        self.verticalLayout.addWidget(self.lineEditOutText)
        self.lblResults = QtWidgets.QLabel(self.centralwidget)
        self.lblResults.setObjectName("lblResults")
        self.verticalLayout.addWidget(self.lblResults, 0, QtCore.Qt.AlignHCenter)
        self.textEditResults = QtWidgets.QTextBrowser(self.centralwidget)
        self.textEditResults.setEnabled(True)
        self.textEditResults.setObjectName("textEditResults")
        self.verticalLayout.addWidget(self.textEditResults)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лавинный эффект"))
        self.lblBlockCount.setText(_translate("MainWindow", "Количество блоков: "))
        self.label_4.setText(_translate("MainWindow", "Выбрать блок №"))
        self.btnChooseBlock.setText(_translate("MainWindow", "Выбрать"))
        self.btnBlocksAverage.setText(_translate("MainWindow", "Усреднить по всем"))
        self.label.setText(_translate("MainWindow", "Блок входного текста"))
        self.label_2.setText(_translate("MainWindow", "Инвертировать бит №"))
        self.btnProcess.setText(_translate("MainWindow", "Преобразовать"))
        self.btnAverage.setText(_translate("MainWindow", "Посчитать среднее"))
        self.label_3.setText(_translate("MainWindow", "Блок выходного текста"))
        self.lblResults.setText(_translate("MainWindow", "Результаты"))

