# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Feistel.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 644)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnSelectTextFile = QtWidgets.QPushButton(self.frame)
        self.btnSelectTextFile.setObjectName("btnSelectTextFile")
        self.verticalLayout_3.addWidget(self.btnSelectTextFile)
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.symbolViewText = QtWidgets.QRadioButton(self.frame_3)
        self.symbolViewText.setObjectName("symbolViewText")
        self.horizontalLayout.addWidget(self.symbolViewText)
        self.hexViewText = QtWidgets.QRadioButton(self.frame_3)
        self.hexViewText.setObjectName("hexViewText")
        self.horizontalLayout.addWidget(self.hexViewText)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.generateFunction1 = QtWidgets.QRadioButton(self.frame_6)
        self.generateFunction1.setObjectName("generateFunction1")
        self.verticalLayout.addWidget(self.generateFunction1)
        self.generateFunction2 = QtWidgets.QRadioButton(self.frame_6)
        self.generateFunction2.setObjectName("generateFunction2")
        self.verticalLayout.addWidget(self.generateFunction2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.blackBox1 = QtWidgets.QRadioButton(self.frame_7)
        self.blackBox1.setObjectName("blackBox1")
        self.verticalLayout_2.addWidget(self.blackBox1)
        self.blackBox2 = QtWidgets.QRadioButton(self.frame_7)
        self.blackBox2.setObjectName("blackBox2")
        self.verticalLayout_2.addWidget(self.blackBox2)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.btnSelectKeyFile = QtWidgets.QPushButton(self.frame)
        self.btnSelectKeyFile.setObjectName("btnSelectKeyFile")
        self.verticalLayout_3.addWidget(self.btnSelectKeyFile)
        self.keyEdit = QtWidgets.QTextEdit(self.frame)
        self.keyEdit.setReadOnly(True)
        self.keyEdit.setObjectName("keyEdit")
        self.verticalLayout_3.addWidget(self.keyEdit)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.symbolsViewKey = QtWidgets.QRadioButton(self.frame_5)
        self.symbolsViewKey.setObjectName("symbolsViewKey")
        self.horizontalLayout_2.addWidget(self.symbolsViewKey)
        self.hexViewKey = QtWidgets.QRadioButton(self.frame_5)
        self.hexViewKey.setObjectName("hexViewKey")
        self.horizontalLayout_2.addWidget(self.hexViewKey)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.checkDecrypt = QtWidgets.QCheckBox(self.frame)
        self.checkDecrypt.setObjectName("checkDecrypt")
        self.verticalLayout_3.addWidget(self.checkDecrypt)
        self.btnProcess = QtWidgets.QPushButton(self.frame)
        self.btnProcess.setObjectName("btnProcess")
        self.verticalLayout_3.addWidget(self.btnProcess)
        self.horizontalLayout_4.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.outEdit = QtWidgets.QTextEdit(self.frame_2)
        self.outEdit.setReadOnly(True)
        self.outEdit.setObjectName("outEdit")
        self.verticalLayout_4.addWidget(self.outEdit)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.symbolsViewOut = QtWidgets.QRadioButton(self.frame_4)
        self.symbolsViewOut.setObjectName("symbolsViewOut")
        self.horizontalLayout_3.addWidget(self.symbolsViewOut)
        self.hexViewOut = QtWidgets.QRadioButton(self.frame_4)
        self.hexViewOut.setObjectName("hexViewOut")
        self.horizontalLayout_3.addWidget(self.hexViewOut)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.btnAvalancheEffect = QtWidgets.QPushButton(self.frame_2)
        self.btnAvalancheEffect.setEnabled(False)
        self.btnAvalancheEffect.setObjectName("btnAvalancheEffect")
        self.verticalLayout_4.addWidget(self.btnAvalancheEffect)
        self.horizontalLayout_4.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Сеть Фейстеля"))
        self.btnSelectTextFile.setText(_translate("MainWindow", "Выбрать файл с текстом"))
        self.symbolViewText.setText(_translate("MainWindow", "Symbols"))
        self.hexViewText.setText(_translate("MainWindow", "Hex"))
        self.generateFunction1.setText(_translate("MainWindow", "Функция генерации ключей 1"))
        self.generateFunction2.setText(_translate("MainWindow", "Функция генерации ключей 2"))
        self.blackBox1.setText(_translate("MainWindow", "Образующая функция 1"))
        self.blackBox2.setText(_translate("MainWindow", "Образующая функция 2"))
        self.btnSelectKeyFile.setText(_translate("MainWindow", "Выбрать файл с ключом"))
        self.symbolsViewKey.setText(_translate("MainWindow", "Symbols"))
        self.hexViewKey.setText(_translate("MainWindow", "Hex"))
        self.checkDecrypt.setText(_translate("MainWindow", "Дешифрование"))
        self.btnProcess.setText(_translate("MainWindow", "Преобразовать"))
        self.symbolsViewOut.setText(_translate("MainWindow", "Symbols"))
        self.hexViewOut.setText(_translate("MainWindow", "Hex"))
        self.btnAvalancheEffect.setText(_translate("MainWindow", "Тестирование лавинного эффекта"))

