# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PrimeNumbers_interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEditBitLength = QtWidgets.QLineEdit(self.frame)
        self.lineEditBitLength.setObjectName("lineEditBitLength")
        self.verticalLayout.addWidget(self.lineEditBitLength)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEditTests = QtWidgets.QLineEdit(self.frame)
        self.lineEditTests.setObjectName("lineEditTests")
        self.verticalLayout.addWidget(self.lineEditTests)
        self.btnGeneratePrime = QtWidgets.QPushButton(self.frame)
        self.btnGeneratePrime.setObjectName("btnGeneratePrime")
        self.verticalLayout.addWidget(self.btnGeneratePrime)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.textBrowserPrime = QtWidgets.QTextBrowser(self.frame)
        self.textBrowserPrime.setObjectName("textBrowserPrime")
        self.verticalLayout.addWidget(self.textBrowserPrime)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEditLow = QtWidgets.QLineEdit(self.frame_4)
        self.lineEditLow.setObjectName("lineEditLow")
        self.horizontalLayout.addWidget(self.lineEditLow)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEditHigh = QtWidgets.QLineEdit(self.frame_5)
        self.lineEditHigh.setObjectName("lineEditHigh")
        self.horizontalLayout_2.addWidget(self.lineEditHigh)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.btnRange = QtWidgets.QPushButton(self.frame_2)
        self.btnRange.setObjectName("btnRange")
        self.verticalLayout_3.addWidget(self.btnRange)
        self.textBrowserRange = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowserRange.setObjectName("textBrowserRange")
        self.verticalLayout_3.addWidget(self.textBrowserRange)
        self.verticalLayout_4.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 435, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генерация простых чисел"))
        self.label_7.setText(_translate("MainWindow", "Генерация простого числа"))
        self.label.setText(_translate("MainWindow", "Битовая длина числа"))
        self.label_2.setText(_translate("MainWindow", "Количество проверок"))
        self.btnGeneratePrime.setText(_translate("MainWindow", "Генерировать"))
        self.label_3.setText(_translate("MainWindow", "Результаты"))
        self.label_6.setText(_translate("MainWindow", "Генерация всех простых чисел из диапазона"))
        self.label_4.setText(_translate("MainWindow", "Нижняя граница"))
        self.label_5.setText(_translate("MainWindow", "Верхняя граница"))
        self.btnRange.setText(_translate("MainWindow", "Генерировать"))

